[versions]
kotlin = "2.2.0"
ktor = "3.2.3"
logback = "1.4.14"
kotlinx-serialization = "1.6.0"
protobuf = "3.25.5"
guava = "33.3.1-jre"
grpc = "1.65.1"
qdrant-client = "1.15.0"
koog = "0.5.3"


[libraries]
# Ktor
ktor-server-core = { module = "io.ktor:ktor-server-core", version.ref = "ktor" }
ktor-server-netty = { module = "io.ktor:ktor-server-netty", version.ref = "ktor" }
ktor-server-cors = { module = "io.ktor:ktor-server-cors", version.ref = "ktor" }
koog-ktor = { module = "ai.koog:koog-ktor", version.ref = "koog" }
ktor-server-content-negotiation = { module = "io.ktor:ktor-server-content-negotiation-jvm", version.ref = "ktor" }
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json-jvm", version.ref = "ktor" }
ktor-server-config-yaml = { module = "io.ktor:ktor-server-config-yaml", version.ref = "ktor" }
ktor-server-test-host = { module = "io.ktor:ktor-server-test-host", version.ref = "ktor" }

# Serialization
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }

# Google
protobuf-java = { module = "com.google.protobuf:protobuf-java", version.ref = "protobuf" }
guava = { module = "com.google.guava:guava", version.ref = "guava" }

# gRPC
grpc-stub = { module = "io.grpc:grpc-stub", version.ref = "grpc" }

# AI/ML
qdrant-client = { module = "io.qdrant:client", version.ref = "qdrant-client" }

# Logging
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }

# Testing
kotlin-test-junit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
ktor = { id = "io.ktor.plugin", version.ref = "ktor" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }